{
 "title": "Aether Edges",
 "tags": [ "aether" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "spgwu,accelleran-cbrs-ric,accelleran-cbrs-nats,accelleran-cbrs-redis,accelleran-cbrs-ricweb"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(kube_pod_info, datacenter)"
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "$pod CPU usage in all Edges",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", pod_name=\"$pod-0\"}[5m])) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "$pod memory usage in all Edges",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\", container_name!=\"\", pod_name=\"$pod-0\"}) by (datacenter)",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "$pod network I/O in all Edges",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=\"$pod-0\",container_name!=\"\"}[5m]))by (datacenter)",
     "legendFormat": "{{ datacenter }} rx"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod_name=\"$pod-0\",container_name!=\"\"}[5m]))by (datacenter)",
     "legendFormat": "{{ datacenter }} tx"
    }
   ]
  },
  { "title": "$pod usage in $datacenter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "datacenter" },
  {
   "title": "$pod CPU usage in $datacenter",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(container_cpu_usage_seconds_total{pod_name=\"$pod-0\", image!=\"\", container_name!=\"POD\", datacenter=\"$datacenter\"}[3m])) by (pod_name) / sum(container_spec_cpu_quota{image!=\"\", container_name!=\"POD\", datacenter=\"$datacenter\"} / container_spec_cpu_period{image!=\"\", container_name!=\"POD\", datacenter=\"$datacenter\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "$pod memory usage in $datacenter",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(container_memory_usage_bytes{pod_name=\"$pod-0\", container_name!=\"POD\", datacenter=\"$datacenter\"}) / sum(container_spec_memory_limit_bytes{pod_name=\"$pod-0\", container_name!=\"POD\", datacenter=\"$datacenter\"}))"
    }
   ]
  },
  {
   "title": "$pod network I/O in $datacenter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=\"$pod-0\", datacenter=\"$datacenter\"}[3m]))by (interface)",
     "legendFormat": "rx: {{ interface }}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{pod_name=\"$pod-0\", datacenter=\"$datacenter\"}[3m]))by (interface)",
     "legendFormat": "tx: {{ interface }}"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{datacenter=\"$datacenter\", pod=\"$pod-0\"})"
    }
   ]
  },
  {
   "title": "CPU used (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", datacenter=\"$datacenter\", pod_name=\"$pod-0\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 33 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{datacenter=\"$datacenter\", pod=\"$pod-0\"})"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 33 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\", container_name!=\"\", datacenter=\"$datacenter\", pod_name=\"$pod-0\"})"
    }
   ]
  }
 ]
}