{
 "title": "Aether Clusters",
 "description": "Monitors Kubernetes clusters using Prometheus.",
 "tags": [ "aether" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(kube_pod_info, datacenter)"
   },
   {
    "name": "Node",
    "query": "label_values(node_load1{datacenter=\"$datacenter\"}, kubernetes_node)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{datacenter=\"$datacenter\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total usage in all data centers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",datacenter!=\"\"}[5m]))by (datacenter))) * 100",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{datacenter!=\"\"})by (datacenter)/ sum(node_memory_MemTotal_bytes{datacenter!=\"\"})by (datacenter)) * 100",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (node_network_receive_bytes_total{datacenter!=\"\"}[5m]))by (datacenter)",
     "legendFormat": "{{ datacenter }} rx"
    },
    {
     "expr": "- sum (rate (node_network_transmit_bytes_total{datacenter!=\"\"}[5m])) by (datacenter)",
     "legendFormat": "{{ datacenter }} tx"
    }
   ]
  },
  {
   "title": "Total usage in $datacenter node $Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU usage (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"})/ sum(node_memory_MemTotal_bytes{datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"})) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"})\n     - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"})) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"}[5m])))) * sum(machine_cpu_cores{datacenter=\"$datacenter\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{datacenter=\"$datacenter\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node =~\"^$Node$\"}) - sum(node_memory_MemAvailable_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node =~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{datacenter=\"$datacenter\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"})\n     - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",datacenter=\"$datacenter\",kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (node_network_receive_bytes_total{datacenter=\"$datacenter\"}[5m]))by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} Received"
    },
    {
     "expr": "- sum (rate (node_network_transmit_bytes_total{datacenter=\"$datacenter\"}[5m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} Sent"
    }
   ]
  },
  {
   "title": "Pods CPU usage in $datacenter namespace $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Pods CPU usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name!=\"\", image!=\"\", container_name!=\"POD\", datacenter=\"$datacenter\", namespace=~\"^$namespace$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage in $datacenter namespace $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\", container_name!=\"\", namespace=~\"^$namespace$\", datacenter=\"$datacenter\"})by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods network I/O in $datacenter namespace $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Pods network I/O (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name!=\"\", container_name!=\"\", datacenter=\"$datacenter\",namespace=~\"^$namespace$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }} Rcvd"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name!=\"\", container_name!=\"\", datacenter=\"$datacenter\",namespace=~\"^$namespace$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }} Sent"
    }
   ]
  }
 ]
}