{
 "title": "Aether Central Pods",
 "tags": [ "aether" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": "mme,hss,spgwc" }
  ]
 },
 "panels": [
  { "title": "$pod usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(container_cpu_usage_seconds_total{pod_name=\"$pod-0\", image!=\"\", container_name!=\"POD\"}[3m])) by (pod_name) / sum(container_spec_cpu_quota{image!=\"\", container_name!=\"POD\"} / container_spec_cpu_period{image!=\"\", container_name!=\"POD\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(container_memory_usage_bytes{pod_name=\"$pod-0\", container_name!=\"POD\"}) / sum(container_spec_memory_limit_bytes{pod_name=\"$pod-0\", container_name!=\"POD\"}))"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=\"$pod-0\", interface!=\"tunl0\"}[3m]))by (interface)",
     "legendFormat": "rx: {{ interface }}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{pod_name=\"$pod-0\", interface!=\"tunl0\"}[3m]))by (interface)",
     "legendFormat": "tx: {{ interface }}"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=\"$pod-0\"})"
    }
   ]
  },
  {
   "title": "CPU used (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", pod_name=\"$pod-0\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod-0\"})"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\", container_name!=\"\", pod_name=\"$pod-0\"})"
    }
   ]
  }
 ]
}