{
 "title": "BNG Accounting Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "onuSerial",
    "label": "ONU Serial",
    "query": "label_values(onosBngControlPackets, onu_serial)"
   },
   { "name": "TimeDelta", "query": "30, 20, 10" },
   { "name": "TimeDeltaS", "query": "30s, 20s, 10s" }
  ]
 },
 "panels": [
  { "title": "ONU: $onuSerial", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "onuSerial" },
  {
   "title": "Total Download (24h)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(onosBngDownTxBytes{onu_serial=\"$onuSerial\"}[24h])) / 1024 / 1024",
     "legendFormat": "Downloaded"
    },
    {}
   ]
  },
  {
   "title": "User Plane (Mbit/s)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "sum(delta(onosBngDownTxBytes{onu_serial=\"$onuSerial\"}[$TimeDeltaS])) * 8 / 1024 / 1024 / $TimeDelta",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(delta(onosBngUpTxBytes{onu_serial=\"$onuSerial\"}[$TimeDeltaS])) * 8 / 1024 / 1024 / $TimeDelta",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Total Upload (24h)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(onosBngUpTxBytes{onu_serial=\"$onuSerial\"}[24h])) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Connection Count (24h)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(delta(onosBngControlPackets{onu_serial=\"$onuSerial\"}[24h]))"
    }
   ]
  },
  {
   "title": "Control Plane (PPPoE control pkt/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(onosBngControlPackets{onu_serial=\"$onuSerial\"}[$TimeDeltaS])) / $TimeDelta",
     "legendFormat": "Upstream Control Packets"
    }
   ]
  }
 ]
}