{
 "title": "OMEC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Pod",
    "label": "Pod",
    "query": "MME, SPGW-C, SPGW-U, HSS, Remote CDN, Remote Streaming, Local CDN"
   }
  ]
 },
 "panels": [
  { "title": "$Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=\"$Pod-0\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(container_cpu_usage_seconds_total{pod_name=\"$Pod-0\"}[3m])) by (pod_name) / sum(container_spec_cpu_quota / container_spec_cpu_period) by (pod_name)"
    },
    {}
   ]
  },
  {
   "title": "Network Traffic (Bytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod_name=\"$Pod-0\"}[3m])) by (interface)",
     "legendFormat": "tx: {{interface}}"
    },
    {
     "expr": "-sum(irate(container_network_receive_bytes_total{pod_name=\"$Pod-0\"}[3m])) by (interface)",
     "legendFormat": "rx: {{interface}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=\"$Pod-0\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(container_memory_usage_bytes{pod_name=\"$Pod-0\"}) / sum(container_spec_memory_limit_bytes{pod_name=\"$Pod-0\"}))"
    }
   ]
  }
 ]
}