{
 "title": "OMEC User Plane",
 "tags": [
  "aether",
  "omec"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(kube_pod_info, datacenter)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{datacenter=\"$site\"},namespace)"
   },
   { "name": "pod", "label": "Pod", "query": "spgwu,accelleran" }
  ]
 },
 "panels": [
  { "title": "$namespace:$pod Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{datacenter=\"$site\", namespace=\"$namespace\", image!=\"\", container_name!=\"POD\", pod_name=~\"$pod.*\"}[5m])) / sum(kube_pod_container_resource_limits_cpu_cores{datacenter=\"$site\", namespace=\"$namespace\", pod=~\"$pod.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(container_memory_usage_bytes{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", container_name!=\"POD\"}) / sum(container_spec_memory_limit_bytes{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", container_name!=\"POD\"}))"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", interface!=\"tunl0\"}[3m]))by (pod_name, interface)",
     "legendFormat": "rx: {{pod_name}}| {{ interface }}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", interface!=\"tunl0\"}[3m]))by (pod_name, interface)",
     "legendFormat": "tx: {{pod_name}}| {{ interface }}"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{datacenter=\"$site\", namespace=\"$namespace\", pod=~\"$pod.*\"})"
    }
   ]
  },
  {
   "title": "CPU used (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{datacenter=\"$site\", namespace=\"$namespace\", image!=\"\", container_name!=\"POD\", pod_name=~\"$pod.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{datacenter=\"$site\", namespace=\"$namespace\", pod=~\"$pod.*\"})"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{datacenter=\"$site\", namespace=\"$namespace\", container_name!=\"POD\", container_name!=\"\", pod_name=~\"$pod.*\"})"
    }
   ]
  },
  {
   "title": "Containers CPU usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",datacenter=\"$site\", namespace=\"$namespace\",pod_name=~\"^$pod-.*\",name=~\"^k8s_.*\",container_name!=\"POD\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",datacenter=\"$site\", namespace=\"$namespace\",pod_name=~\"^$pod.*\",name=~\"^k8s_.*\",container_name!=\"POD\"}) by (container_name, pod_name)",
     "legendFormat": "{{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  { "title": "$namespace:$pod Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{datacenter=\"$site\", namespace=\"$namespace\", image!=\"\", container_name!=\"POD\", pod_name=~\"$pod.*\"}[5m])) / sum(kube_pod_container_resource_limits_cpu_cores{datacenter=\"$site\", namespace=\"$namespace\", pod=~\"$pod.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(container_memory_usage_bytes{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", container_name!=\"POD\"}) / sum(container_spec_memory_limit_bytes{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", container_name!=\"POD\"}))"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", interface!=\"tunl0\"}[3m]))by (pod_name, interface)",
     "legendFormat": "rx: {{pod_name}}| {{ interface }}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{datacenter=\"$site\", namespace=\"$namespace\", pod_name=~\"$pod.*\", interface!=\"tunl0\"}[3m]))by (pod_name, interface)",
     "legendFormat": "tx: {{pod_name}}| {{ interface }}"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{datacenter=\"$site\", namespace=\"$namespace\", pod=~\"$pod.*\"})"
    }
   ]
  },
  {
   "title": "CPU used (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{datacenter=\"$site\", namespace=\"$namespace\", image!=\"\", container_name!=\"POD\", pod_name=~\"$pod.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{datacenter=\"$site\", namespace=\"$namespace\", pod=~\"$pod.*\"})"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{datacenter=\"$site\", namespace=\"$namespace\", container_name!=\"POD\", container_name!=\"\", pod_name=~\"$pod.*\"})"
    }
   ]
  },
  {
   "title": "Containers CPU usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",datacenter=\"$site\", namespace=\"$namespace\",pod_name=~\"^$pod-.*\",name=~\"^k8s_.*\",container_name!=\"POD\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",datacenter=\"$site\", namespace=\"$namespace\",pod_name=~\"^$pod.*\",name=~\"^k8s_.*\",container_name!=\"POD\"}) by (container_name, pod_name)",
     "legendFormat": "{{ pod_name }} | {{ container_name }}"
    }
   ]
  }
 ]
}