{
 "title": "ONOS KPIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "label_values(onos_rx_packets_total, device_id)"
   }
  ]
 },
 "panels": [
  { "title": "Device $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device" },
  {
   "title": "Received MB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onos_rx_bytes_total{device_id=\"$device\"} / 1024 / 1024",
     "legendFormat": "{{ device_id }}:{{ port_id }}"
    }
   ]
  },
  {
   "title": "Transmitted MB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onos_tx_bytes_total{device_id=\"$device\"} / 1024 / 1024",
     "legendFormat": "{{ device_id }}:{{ port_id }}"
    }
   ]
  },
  {
   "title": "Received Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onos_rx_packets_total{device_id=\"$device\"}",
     "legendFormat": "{{ device_id }}:{{ port_id }}"
    }
   ]
  },
  {
   "title": "Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onos_tx_packets_total{device_id=\"$device\"}",
     "legendFormat": "{{ device_id }}:{{ port_id }}"
    }
   ]
  },
  {
   "title": "Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onos_rx_drop_packets_total{device_id=\"$device\"}",
     "legendFormat": "{{ device_id }}:{{ port_id }}"
    }
   ]
  },
  {
   "title": "Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onos_tx_drop_packets_total{device_id=\"$device\"}",
     "legendFormat": "{{ device_id }}:{{ port_id }}"
    }
   ]
  }
 ]
}