{
 "title": "SD-RAN: a Summary",
 "tags": [
  "ONOS-RIC",
  "Handover",
  "LoadBalancing"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Connected UEs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "total_num_ues" }
   ]
  },
  {
   "title": "Number of Connected UEs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# Connected UEs" }
   ],
   "targets": [
    { "expr": "total_num_ues" }
   ]
  },
  {
   "title": "Number of Connected eNBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# Connected eNBs" }
   ],
   "targets": [
    { "expr": "total_num_bses" }
   ]
  },
  {
   "title": "Number of Connected eNBs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "total_num_bses" }
   ]
  },
  { "title": "Handover Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Handovers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "onosproject_ransimulator_hometrics_count"
    }
   ]
  },
  {
   "title": "Number of Handover Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "# HO Events" }
   ],
   "targets": [
    {
     "expr": "onosproject_ransimulator_hometrics_count"
    }
   ]
  },
  {
   "title": "Average E2E Handover Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "onosproject_ransimulator_hometrics_sum / onosproject_ransimulator_hometrics_count"
    }
   ]
  },
  {
   "title": "Average E2E HO Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "onosproject_ransimulator_hometrics_sum / onosproject_ransimulator_hometrics_count"
    }
   ]
  },
  {
   "title": "Average E2E HO Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[1m]) / rate(onosproject_ransimulator_hometrics_count[1m])"
    }
   ]
  },
  {
   "title": "Last 1min Average E2E Handover Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[1m]) / rate(onosproject_ransimulator_hometrics_count[1m])"
    }
   ]
  },
  {
   "title": "Last 1min 90% E2E Handover Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "90% E2E HO Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "95% E2E HO Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Last 1min 95% E2E Handover Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Last 1min 99% E2E Handover Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "99% E2E HO Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))"
    }
   ]
  },
  { "title": "Load Balancing Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "STDEV(#UEs) among eNBs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 35 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "stdev_ues" }
   ]
  },
  {
   "title": "90% LB App Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "95% LB App Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "STDEV(#UEs) among eNBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Standard Deviation" }
   ],
   "targets": [
    { "expr": "stdev_ues" }
   ]
  },
  {
   "title": "Number of LB Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mlbapp_mlb_histogram_count" }
   ]
  },
  {
   "title": "Average LB App Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 39 },
   "targets": [
    {
     "expr": "mlbapp_mlb_histogram_sum / mlbapp_mlb_histogram_count"
    }
   ]
  },
  {
   "title": "Average LB App Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 39 },
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[1m]) / rate(mlbapp_mlb_histogram_count[1m])"
    }
   ]
  },
  {
   "title": "99% LB App Latency [last 1m]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Number of Load Balancing Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "# LB Events" }
   ],
   "targets": [
    { "expr": "mlbapp_mlb_histogram_count" }
   ]
  },
  {
   "title": "Average LB App Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "mlbapp_mlb_histogram_sum / mlbapp_mlb_histogram_count"
    }
   ]
  },
  {
   "title": "Last 1 min Average LB App Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[1m]) / rate(mlbapp_mlb_histogram_count[1m])"
    }
   ]
  },
  {
   "title": "Last 1 min 90% LB App Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Last 1 min 95% LB App Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Last 1 min 99% LB App Latency [µs]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Latency [µs]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))"
    }
   ]
  }
 ]
}