{
 "title": "SD-RAN: Detailed MLB Information",
 "tags": [
  "ONOS-RIC",
  "LoadBalancing"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Load Balancing Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Balancing Interval",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "format": "µs",
     "valueName": "current",
     "targets": [
      { "expr": "mlbapp_mlb_param_period" }
     ]
    },
    {
     "title": "Load Balancing Interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 1 },
     "yaxes": [
      { "format": "µs", "label": "Interval" }
     ],
     "targets": [
      { "expr": "mlbapp_mlb_param_period" }
     ]
    },
    {
     "title": "Load Balancing Threshold",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
     "yaxes": [
      { "format": "percentunit", "label": "Threshold" }
     ],
     "targets": [
      { "expr": "mlbapp_mlb_param_threshold" }
     ]
    },
    {
     "title": "Load Balancing Threshold",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      { "expr": "mlbapp_mlb_param_threshold" }
     ]
    }
   ]
  },
  {
   "title": "Load Balancing Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Cells",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "mlbapp_total_num_stas" }
     ]
    },
    {
     "title": "Number of Cells",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 2 },
     "yaxes": [
      { "format": "none", "label": "Number of Cells" }
     ],
     "targets": [
      { "expr": "mlbapp_total_num_stas" }
     ]
    },
    {
     "title": "Number of Cells",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 2 },
     "yaxes": [
      { "format": "none", "label": "Number of Cells" }
     ],
     "targets": [
      { "expr": "mlbapp_total_num_stas" }
     ]
    },
    {
     "title": "Number of UEs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "mlbapp_total_num_ues" }
     ]
    },
    {
     "title": "Number of UEs per Each Cell",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none", "label": "Number of UEs" }
     ],
     "targets": [
      { "expr": "mlbapp_num_ues_per_sta", "legendFormat": "{{ staid }}" }
     ]
    },
    {
     "title": "Average Number of UEs / Cell",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "mlbapp_total_num_ues / mlbapp_total_num_stas"
      }
     ]
    },
    {
     "title": "Average and Standard Deviation of Number of UEs / Cell",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mlbapp_total_num_ues / mlbapp_total_num_stas",
       "legendFormat": "Average"
      },
      { "expr": "mlbapp_load_stdev", "legendFormat": "Standard Deviation" }
     ]
    },
    {
     "title": "Standard Deviation of Number of UEs / Cell",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "mlbapp_load_stdev" }
     ]
    }
   ]
  },
  { "title": "Load Balancing Event Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Number of LB Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mlbapp_mlb_histogram_count" }
   ]
  },
  {
   "title": "Number of MLB Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "# MLB Events" }
   ],
   "targets": [
    { "expr": "mlbapp_mlb_histogram_count" }
   ]
  },
  {
   "title": "MLB Rate [Last 1m]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_count[1m])"
    }
   ]
  },
  {
   "title": "MLB Rate [Last 5m]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_count[5m])"
    }
   ]
  },
  {
   "title": "MLB Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "# HO Events" }
   ],
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_count[$__interval])",
     "legendFormat": "Real Time"
    },
    {
     "expr": "rate(mlbapp_mlb_histogram_count[1m])",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "rate(mlbapp_mlb_histogram_count[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "rate(mlbapp_mlb_histogram_count[1h])",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "MLB Rate [Last 1h]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_count[1h])"
    }
   ]
  },
  { "title": "Overall Load Balancing Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average MLB Latency in MLBApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "mlbapp_mlb_histogram_sum / mlbapp_mlb_histogram_count"
    }
   ]
  },
  {
   "title": "MLB Latency in MLBApp [Overall]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "µs", "label": "MLB Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "mlbapp_mlb_histogram_sum / mlbapp_mlb_histogram_count",
     "legendFormat": "Average MLB Latency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(mlbapp_mlb_histogram_bucket) by (le))",
     "legendFormat": "90% MLB Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(mlbapp_mlb_histogram_bucket) by (le))",
     "legendFormat": "95% MLB Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(mlbapp_mlb_histogram_bucket) by (le))",
     "legendFormat": "99% MLB Latency"
    },
    {
     "expr": "histogram_quantile(1, sum(mlbapp_mlb_histogram_bucket) by (le))",
     "legendFormat": "Max MLB Latency"
    }
   ]
  },
  {
   "title": "90% MLB Latency in MLBApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(mlbapp_mlb_histogram_bucket) by (le))"
    }
   ]
  },
  {
   "title": "95% MLB Latency in MLBApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(mlbapp_mlb_histogram_bucket) by (le))"
    }
   ]
  },
  {
   "title": "99% MLB Latency in MLBApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(mlbapp_mlb_histogram_bucket) by (le))"
    }
   ]
  },
  {
   "title": "Max MLB Latency in MLBApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(mlbapp_mlb_histogram_bucket) by (le))"
    }
   ]
  },
  {
   "title": "Last 1m/5m/1h Load Balancing Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Average MLB Latency in MLBApp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[1m]) / rate(mlbapp_mlb_histogram_count[1m])",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[5m]) / rate(mlbapp_mlb_histogram_count[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[1h]) / rate(mlbapp_mlb_histogram_count[1h])",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "Average MLB Latency in MLBApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "µs", "label": "MLB Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[1m]) / rate(mlbapp_mlb_histogram_count[1m])",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[5m]) / rate(mlbapp_mlb_histogram_count[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "rate(mlbapp_mlb_histogram_sum[1h]) / rate(mlbapp_mlb_histogram_count[1h])",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "90% MLB Latency in MLBApp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "90% MLB Latency in MLBApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "µs", "label": "MLB Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "95% MLB Latency in MLBApp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "95% MLB Latency in MLBApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "µs", "label": "MLB Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "99% MLB Latency in MLBApp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "99% MLB Latency in MLBApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "µs", "label": "MLB Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "Max MLB Latency in MLBApp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "Max MLB Latency in MLBApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 65 },
   "yaxes": [
    { "format": "µs", "label": "MLB Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mlbapp_mlb_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(mlbapp_mlb_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(mlbapp_mlb_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h"
    }
   ]
  }
 ]
}