{
 "title": "SD-RAN: Detailed Handover Information",
 "tags": [
  "ONOS-RIC",
  "Handover"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "A3 Handover Parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "A3 Offset",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "hoapp_ho_param_a3offset" }
   ]
  },
  {
   "title": "A3 Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CQI" }
   ],
   "targets": [
    { "expr": "hoapp_ho_param_a3offset" }
   ]
  },
  {
   "title": "A3 Hysteresis",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CQI" }
   ],
   "targets": [
    { "expr": "hoapp_ho_param_hysteresis" }
   ]
  },
  {
   "title": "A3 Time-To-Trigger",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "time [ms]" }
   ],
   "targets": [
    { "expr": "hoapp_ho_param_ttt" }
   ]
  },
  {
   "title": "A3 Hysteresis",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "hoapp_ho_param_hysteresis" }
   ]
  },
  {
   "title": "A3 Time-To-Trigger",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "hoapp_ho_param_ttt" }
   ]
  },
  { "title": "Handover Event Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Number of Handovers [Overall]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "hoapp_ho_histogram_count" }
   ]
  },
  {
   "title": "Number of Handover Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "# HO Events" }
   ],
   "targets": [
    {
     "expr": "onosproject_ransimulator_hometrics_count"
    }
   ]
  },
  {
   "title": "Handover Rate [Last 1m]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(hoapp_ho_histogram_count[1m])"
    }
   ]
  },
  {
   "title": "Handover Rate [Last 5m]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(hoapp_ho_histogram_count[5m])"
    }
   ]
  },
  {
   "title": "Handover Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "# HO Events" }
   ],
   "targets": [
    {
     "expr": "rate(hoapp_ho_histogram_count[$__interval])",
     "legendFormat": "Real Time"
    },
    {
     "expr": "rate(hoapp_ho_histogram_count[1m])",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "rate(hoapp_ho_histogram_count[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "rate(hoapp_ho_histogram_count[1h])",
     "legendFormat": "Last 1h"
    }
   ]
  },
  {
   "title": "Handover Rate [Last 1h]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(hoapp_ho_histogram_count[1h])"
    }
   ]
  },
  { "title": "Overall Handover Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "last_time_window" },
  {
   "title": "Average E2E HO Latency [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "onosproject_ransimulator_hometrics_sum / onosproject_ransimulator_hometrics_count"
    }
   ]
  },
  {
   "title": "Average Handover Latency [Overall]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 28 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "onosproject_ransimulator_hometrics_sum / onosproject_ransimulator_hometrics_count",
     "legendFormat": "E2E Handover Latency"
    },
    {
     "expr": "hoapp_ho_histogram_sum / hoapp_ho_histogram_count",
     "legendFormat": "Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "Average HO Latency in HOApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "hoapp_ho_histogram_sum / hoapp_ho_histogram_count"
    }
   ]
  },
  {
   "title": "90% E2E HO Latency [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(onosproject_ransimulator_hometrics_bucket) by (le))"
    }
   ]
  },
  {
   "title": "90% Handover Latency [Overall]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 36 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(onosproject_ransimulator_hometrics_bucket) by (le))",
     "legendFormat": "E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(hoapp_ho_histogram_bucket) by (le))",
     "legendFormat": "Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "90% HO Latency in HOApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(hoapp_ho_histogram_bucket) by (le))"
    }
   ]
  },
  {
   "title": "95% E2E HO Latency [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(onosproject_ransimulator_hometrics_bucket) by (le))"
    }
   ]
  },
  {
   "title": "95% Handover Latency [Overall]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 44 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(onosproject_ransimulator_hometrics_bucket) by (le))",
     "legendFormat": "E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(hoapp_ho_histogram_bucket) by (le))",
     "legendFormat": "Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "95% HO Latency in HOApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(hoapp_ho_histogram_bucket) by (le))"
    }
   ]
  },
  {
   "title": "99% E2E HO Latency [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(onosproject_ransimulator_hometrics_bucket) by (le))"
    }
   ]
  },
  {
   "title": "99% Handover Latency [Overall]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 52 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(onosproject_ransimulator_hometrics_bucket) by (le))",
     "legendFormat": "E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(hoapp_ho_histogram_bucket) by (le))",
     "legendFormat": "Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "99% HO Latency in HOApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(hoapp_ho_histogram_bucket) by (le))"
    }
   ]
  },
  {
   "title": "Max E2E HO Latency [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(onosproject_ransimulator_hometrics_bucket) by (le))"
    }
   ]
  },
  {
   "title": "Max Handover Latency [Overall]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 60 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(onosproject_ransimulator_hometrics_bucket) by (le))",
     "legendFormat": "E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(1, sum(hoapp_ho_histogram_bucket) by (le))",
     "legendFormat": "Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "Max HO Latency in HOApp [Overall]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(hoapp_ho_histogram_bucket) by (le))"
    }
   ]
  },
  { "title": "Last 1m/5m/1h Handover Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Average E2E HO Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[1m]) / rate(onosproject_ransimulator_hometrics_count[1m])",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[5m]) / rate(onosproject_ransimulator_hometrics_count[5m])",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[1h]) / rate(onosproject_ransimulator_hometrics_count[1h])",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "Average Handover Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 69 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[1m]) / rate(onosproject_ransimulator_hometrics_count[1m])",
     "legendFormat": "Last 1m E2E Handover Latency"
    },
    {
     "expr": "rate(hoapp_ho_histogram_sum[1m]) / rate(hoapp_ho_histogram_count[1m])",
     "legendFormat": "Last 1m Handover Latency in HOApp"
    },
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[5m]) / rate(onosproject_ransimulator_hometrics_count[5m])",
     "legendFormat": "Last 5m E2E Handover Latency"
    },
    {
     "expr": "rate(hoapp_ho_histogram_sum[5m]) / rate(hoapp_ho_histogram_count[5m])",
     "legendFormat": "Last 5m Handover Latency in HOApp"
    },
    {
     "expr": "rate(onosproject_ransimulator_hometrics_sum[1h]) / rate(onosproject_ransimulator_hometrics_count[1h])",
     "legendFormat": "Last 1h E2E Handover Latency"
    },
    {
     "expr": "rate(hoapp_ho_histogram_sum[1h]) / rate(hoapp_ho_histogram_count[1h])",
     "legendFormat": "Last 1h Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "Average HO Latency in HOApp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rate(hoapp_ho_histogram_sum[1m]) / rate(hoapp_ho_histogram_count[1m])",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "rate(hoapp_ho_histogram_sum[5m]) / rate(hoapp_ho_histogram_count[5m])",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "rate(hoapp_ho_histogram_sum[1h]) / rate(hoapp_ho_histogram_count[1h])",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "90% E2E HO Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[5m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[1h])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "90% Handover Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 77 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[5m])) by (le))",
     "legendFormat": "Last 5m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hoapp_ho_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(onosproject_ransimulator_hometrics_bucket[1h])) by (le))",
     "legendFormat": "Last 1h E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hoapp_ho_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "90% HO Latency in HOApp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "95% E2E HO Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "95% Handover Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 85 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[5m])) by (le))",
     "legendFormat": "Last 5m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hoapp_ho_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(onosproject_ransimulator_hometrics_bucket[1h])) by (le))",
     "legendFormat": "Last 1h E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hoapp_ho_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "95% HO Latency in HOApp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hoapp_ho_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hoapp_ho_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "99% E2E HO Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[5m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[1h])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "99% Handover Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 93 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[5m])) by (le))",
     "legendFormat": "Last 5m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hoapp_ho_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(onosproject_ransimulator_hometrics_bucket[1h])) by (le))",
     "legendFormat": "Last 1h E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hoapp_ho_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "99% HO Latency in HOApp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hoapp_ho_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hoapp_ho_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "Max E2E HO Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(onosproject_ransimulator_hometrics_bucket[5m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(onosproject_ransimulator_hometrics_bucket[1h])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  },
  {
   "title": "Max Handover Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 101 },
   "yaxes": [
    { "format": "µs", "label": "HO Latency [ms]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(onosproject_ransimulator_hometrics_bucket[1m])) by (le))",
     "legendFormat": "Last 1m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(onosproject_ransimulator_hometrics_bucket[5m])) by (le))",
     "legendFormat": "Last 5m E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(hoapp_ho_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5m Handover Latency in HOApp"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(onosproject_ransimulator_hometrics_bucket[1h])) by (le))",
     "legendFormat": "Last 1h E2E Handover Latency"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(hoapp_ho_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1h Handover Latency in HOApp"
    }
   ]
  },
  {
   "title": "Max HO Latency in HOApp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(hoapp_ho_histogram_bucket[1m])) by (le))",
     "legendFormat": "Last 1min"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(hoapp_ho_histogram_bucket[5m])) by (le))",
     "legendFormat": "Last 5min"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(hoapp_ho_histogram_bucket[1h])) by (le))",
     "legendFormat": "Last 1hour"
    }
   ]
  }
 ]
}