{
 "title": "Voltha",
 "description": "Display KPIs as collected by VOLTHA",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "olt",
    "label": "OLT Device",
    "query": "label_values(tx_bytes_total, logical_device_id)"
   },
   {
    "name": "onu",
    "query": "label_values(tx_packets_total{title=\"Ethernet_Bridge_Port_History\"}, serial_number)"
   }
  ]
 },
 "panels": [
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transmitted MB by device",
   "type": "graph",
   "description": "Count the tx bytes on the NNI ports by device",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tx_bytes_total{title=\"Ethernet\"})by(logical_device_id)  / 1024 / 1024",
     "legendFormat": "{{logical_device_id}}"
    }
   ]
  },
  {
   "title": "Received MB by device",
   "type": "graph",
   "description": "Count the rx bytes on the NNI ports by device",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rx_bytes_total{title=\"Ethernet\"})by(logical_device_id) / 1024 / 1024",
     "legendFormat": "{{logical_device_id}}"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Transmitted packets by device",
   "type": "graph",
   "description": "Count the tx packets on the NNI ports by device",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tx_packets_total{title=\"Ethernet\"})by(logical_device_id)",
     "legendFormat": "{{logical_device_id}}"
    }
   ]
  },
  {
   "title": "Received packets by device",
   "type": "graph",
   "description": "Count the rx packets on the NNI ports by device",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rx_packets_total{title=\"Ethernet\"})by(logical_device_id)",
     "legendFormat": "{{logical_device_id}}"
    }
   ]
  },
  { "title": "Realtime Traffic Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Realtime Incoming MB by NNI port",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(rx_bytes_total{title=\"Ethernet\"}[30s]) / 1024 / 1024",
     "legendFormat": "{{logical_device_id}}"
    }
   ]
  },
  { "title": "Per device informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Received MB per PON on device $olt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "repeat": "olt",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rx_bytes_total{title=\"PON\", logical_device_id=\"$olt\"} / 1024 / 1024",
     "legendFormat": "{{pon_id}}"
    }
   ]
  },
  {
   "title": "Transmitted MB per PON on device $olt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "repeat": "olt",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tx_bytes_total{title=\"PON\", logical_device_id=\"$olt\"} / 1024 / 1024",
     "legendFormat": "{{pon_id}}"
    }
   ]
  },
  {
   "title": "ONU Transmitted Bytes on $onu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tx_bytes_total{title=\"Ethernet_Bridge_Port_History\", serial_number=\"$onu\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "ONU Transmitted Packets on $onu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tx_packets_total{title=\"Ethernet_Bridge_Port_History\", serial_number=\"$onu\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "ONU Received Bytes on $onu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rx_bytes_total{title=\"Ethernet_Bridge_Port_History\", serial_number=\"$onu\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "ONU Received Packets on $onu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rx_packets_total{title=\"Ethernet_Bridge_Port_History\", serial_number=\"$onu\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  }
 ]
}