{
 "title": "VOLTHA-2.X",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total number of messages over Kafka",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_messagesinpersec_count{}"
    }
   ]
  },
  {
   "title": "ETCD: Total msg received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(grpc_server_msg_received_total{instance=\"voltha-etcd-cluster.voltha.svc:2379\"})"
    }
   ]
  },
  {
   "title": "ETCD: Total msg sent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(grpc_server_msg_sent_total{instance=\"voltha-etcd-cluster.voltha.svc:2379\"})"
    }
   ]
  },
  {
   "title": "Kafka MSG per topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesinpersec_count{}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ETCD: Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_msg_received_total{instance=\"voltha-etcd-cluster.voltha.svc:2379\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(grpc_server_msg_sent_total{instance=\"voltha-etcd-cluster.voltha.svc:2379\"})",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}