{
 "title": "XOS",
 "description": "Monitoring XOS Activities",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "model",
    "query": "label_values(grpc_request_count_total, model_name)"
   },
   {
    "name": "request_status",
    "query": "label_values(grpc_request_count_total, status)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average request duration in the last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_request_latency_seconds_sum[5m]) / rate(grpc_request_latency_seconds_count[5m])",
     "legendFormat": "{{model_name}} - {{endpoint}}"
    }
   ]
  },
  { "title": "Requests by status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total requests resulted in $request_status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "repeat": "request_status",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(grpc_request_count_total{status=\"StatusCode.$request_status\"})"
    }
   ]
  },
  {
   "title": "Total requests resulted in $request_status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(grpc_request_count_total{status=\"StatusCode.$request_status\"})"
    }
   ]
  },
  {
   "title": "Total requests resulted in $request_status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(grpc_request_count_total{status=\"StatusCode.$request_status\"})"
    }
   ]
  },
  { "title": "Requests per model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "repeat": "model",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests for model $model",
   "type": "graph",
   "description": "List all the request related to this model",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_request_count_total{model_name=\"$model\"}",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  }
 ]
}