{{/*
Copyright 2018-present Open Networking Foundation
Copyright 2018 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: omec-sriov-plugin
  labels:
{{ tuple "omec-sriov-plugin" . | include "omec-data-plane-cni.metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple "omec-sriov-plugin" . | include "omec-data-plane-cni.metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple "omec-sriov-plugin" . | include "omec-data-plane-cni.metadata_labels" | indent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      initContainers:
      - name: init-omec-sriov-plugin
        image: {{ .Values.images.tags.omecCni }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        command: [ "bash", "-c" ]
        args:
        - cp /tmp/cni/bin/{sriov,vfioveth,jq,static} /host/opt/cni/bin/
        volumeMounts:
        - name: cni-bin
          mountPath: /host/opt/cni/bin
      containers:
      - name: sriov-device-plugin
        image: {{ .Values.images.tags.sriovPlugin }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "sriovdp --logtostderr 10;" ]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: devicesock
          readOnly: false
        - mountPath: /sys
          name: net
          readOnly: true
        - name: sriov-config
          mountPath: /etc/pcidp
      volumes:
      - name: devicesock
        hostPath:
          path: /var/lib/kubelet/
      - name: net
        hostPath:
          path: /sys
      - name: sriov-config
        configMap:
          name: sriov-config
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
