---
# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ponsim-pod
description: A Helm chart for loading the Ponsim pod's TOSCA files into XOS
icon: https://guide.opencord.org/logos/xos.svg

version: 1.3.3

# xosproject/tosca-loader version
appVersion: 1.3.1
