{{- /*
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/ -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accelleran-cbrs-ric-cm
  labels:
{{ tuple "accelleran-cbrs-ric-cm" . | include "accelleran-cbrs-common.metadata_labels" | indent 4 }}
data:
  bootstrap: |
    redis.hostname:accelleran-cbrs-redis
    redis.port:{{ .Values.config.redis.ports.redisPort.port }}
    instance.filter:{{ .Values.config.ric.instanceId }}

  zlog.conf: |
    [global]
    strict init = true
    buffer min = {{ .Values.config.ric.zlogConf.bufferMin }}
    buffer max = {{ .Values.config.ric.zlogConf.bufferMax }}
    rotate lock file = /tmp/zlog.lock

    [formats]
    printf_format = "%d(%b %d %H:%M:%S).%ms %8.8H %m%n"
    [rules]
    user.* >stdout ;printf_format